### ISSUE TITLE
Styling issues with deck.js's "web 2.0" theme

### ISSUE THREAD

**Issue by jblashill** [iros/deck.js-codemirror#24]
Just installed your extension and it looks like the "web-2.0" theme of deck.js doesn't play nice with codemirror styles. There may not be much you can do about it short of hacking in some CSS to undo "web-2.0" styling where codemirror styles are present. But I just wanted to bring it to your attention..

![deckjscodemirrorbug](https://f.cloud.github.com/assets/1558017/642298/563b904e-d355-11e2-84aa-556761b1c88e.png)

**Comment by jblashill** [comment]
If it's useful to anyone, here are the css "undos" I added to my deck.js presentation's CSS to fix the above styling issues:

``` css
.deck-container .slide .CodeMirror-lines {
    background: white;
}

.csstransforms.boxshadow .deck-container .slide .CodeMirror pre:before,
.csstransforms.boxshadow .deck-container .slide .CodeMirror pre:after {
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
}
```
